### ISSUE TITLE
How to deploy on CentOS

### ISSUE THREAD

**Issue by ubill88** [openstreetmap/cgimap#6]
Hi, I'm a new user that using a CentOS server.
I'm facing a problem to start CGImap on apache2.
There is no apache2 but only httpd on CentOS, and there is no a2ensite either.
I've been able to run
`./openstreetmap-cgimap --socket :54321 --backend apidb \
  --dbname openstreetmap`
But I don't have any clue about the apache2 part.
Also, **cgimap/scripts/cgimap.conf** seems not working on **/etc/httpd/sites-available/**
Is there an example about deploying on CentOS?
Please give me a hint! Thanks in advance!

Best regards.

**Comment by mmd-osm** [comment]
Question was answered here: https://github.com/zerebubuth/openstreetmap-cgimap/issues/243
